export { AssistantError } from "./errors";
export type { AssistantErrorCode } from "./errors";
export { DEFAULT_OLLAMA_URL, OllamaClient, listModels } from "./ollama";
export type { ChatMessage, ChatOptions, InstalledModel, LanguageModel, OllamaSettings } from "./ollama";
export { DEFAULT_ATTEMPTS, MAX_REQUEST_CHARS, designCircuit } from "./design";
export type { AttemptInfo, Design, DesignOptions, DesignRequest } from "./design";
export { namesAskedFor, onlyGateAskedFor, requestProblems } from "./checks";
export { MAX_DESCRIBED_GATES, describeCircuit } from "./describe";
export type { Description } from "./describe";
export { MAX_INPUTS, MAX_TABLE_INPUTS, buildCircuit } from "./build";
export type { BuildResult, CircuitSpec, Definition } from "./build";
export { EXAMPLES_PER_PROMPT, RECIPES, recipesFor } from "./cookbook";
export type { Recipe } from "./cookbook";
export { repairMessage, requestMessage, systemPrompt } from "./prompt";
export { SPEC_SCHEMA, readAnswer, writeAnswer } from "./spec";
export type { Answer } from "./spec";
export { GATE_FUNCTIONS, FormulaError, RESERVED_WORDS, applyGate, evaluateFormula, namesIn, parseFormula, printFormula } from "./formula";
export type { BinaryOperator, Formula, GateFunction } from "./formula";
export { minimize } from "./minimize";
export type { Literal, Term } from "./minimize";
